import logging

KHL_API_BASEURL = "https://www.kaiheila.cn/api"

KHL_API_GATEWAY = "/v3/gateway/index"
KHL_API_CREATE_MSG = "/v3/message/create"

LOGGING_FILE_LEVEL = logging.WARNING
LOGGING_CONSOLE_LEVEL = logging.INFO

# configurable items for bot
MAX_PROCESSING_NUMBER = "MAX_PROCESSING_NUMBER"
MAX_CONSUMER_NUMBER = "MAX_CONSUME_NUMBER"
MAX_EVENT_QUEUE_SIZE = "MAX_EVENT_QUEUE_SIZE"
PROCESSING_IDLE_TIMEOUT = "PROCESSING_IDLE_TIMEOUT"

# khl message type
KHL_MSG_TEXT = 1
KHL_MSG_CARD = 10
KHL_MSG_MARKDOWN = 9
